test_factorial (__main__.TestExercice) ... ERROR
test_prefixes (__main__.TestExercice) ... FAIL
test_summation (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_factorial (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 44, in test_factorial
    output = [exercice.factorial(v) for v in values]
  File "test_exercice.py", line 44, in <listcomp>
    output = [exercice.factorial(v) for v in values]
  File "/home/runner/work/c01_ch5_exercices-simo255/c01_ch5_exercices-simo255/exercice.py", line 23, in factorial
    return math.factorial()
NameError: name 'math' is not defined

======================================================================
FAIL: test_prefixes (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 20, in test_prefixes
    'Mauvaise identification de la parité de la longueur de la chaine'
AssertionError: Lists differ: [''] != ['Jack', 'Kack', 'Lack', 'Mack', 'Nack', 'Oack', 'Pack', 'Qack']

First differing element 0:
''
'Jack'

Second list contains 7 additional elements.
First extra element 1:
'Kack'

- ['']
+ ['Jack', 'Kack', 'Lack', 'Mack', 'Nack', 'Oack', 'Pack', 'Qack'] : Mauvaise identification de la parité de la longueur de la chaine

======================================================================
FAIL: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 38, in test_summation
    'Retrait du mauvais caractère'
AssertionError: 0 != 24133 : Retrait du mauvais caractère

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=2, errors=1)
